server:
  port: 8080

spring:
  profiles:
    active: @spring.active@
  jpa:
    database: mysql
#    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB